version: "3.9"
services:
  db:
    image: mongo:latest
    container_name: mongo-latest
    volumes:
      - $HOME/Documents/docker/mongodb-data:/data/db
    ports:
      - "27018:27017"
    networks: 
      - network-db-mongo
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/blog-mongo
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks: 
      - network-db-mongo
networks: 
  network-db-mongo:
