version: "3.9"
services:
  # docker compose db nya udah di create di lainnya
  db:
    image: mongo:latest
    container_name: mongo-blog
    environment:
          - TZ='Asia/Jakarta'
          - MONGO_INITDB_ROOT_USERNAME="grumpycat"
          - MONGO_INITDB_ROOT_PASSWORD="alo123"
    command: [--auth]
    volumes:
      - $HOME/Documents/docker/mongodb/blog-mongodb:/data/db/
      # - mongo:/data/db
      # - mongo:/data/configdb
      #move init-mongo.js to inside docker foler docker-entrypoint-initdb.d
      #- ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27018:27017"
    networks: 
      - network-db-mongo-1
  app:
    build: .
    image: lukmanbap/blog-mongo-app
    container_name: app
    tty: true
    environment:
      - RAILS_ENV='production'
      - RAILS_SERVE_STATIC_FILES=true
    command: ["nginx"]
    volumes:
      - ./:/var/www/html/blog_mongo.com
    ports:
      - 80:8080
      - 443:8443
      - 3000:3000
    # docker compose db nya udah di create di lainnya
    depends_on:
      - db
    networks: 
      - network-db-mongo-1
volumes:
  mongo:
    driver: local
networks: 
  network-db-mongo-1:
  default:
    external:
      name: network-db-mongo-1
